config/routes.rb
Tkiero::Application.routes.draw do
  get "signup" => "users#new", :as => "signup"
  resources :users

  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  resources :sessions

  root to: 'static_pages#home'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id            :integer         not null, primary key
#  name          :string(255)
#  email         :string(255)
#  password_hash :string(255)
#  password_salt :string(255)
#  created_at    :datetime        not null
#  updated_at    :datetime        not null
#

class User < ActiveRecord::Base
    #only allow access to this fields from the internet 
    attr_accessible :name, :email, :password, :password_confirmation

    # Creates an instance variable for :password submitted by the HTML Form, and validate password_confirmation 
    attr_accessor :password
    validates_confirmation_of :password
    
    #Calls encrypt_password method to encrypt before saving the user model    
    before_save :encrypt_password
    
    # Downloadcase before save email to avoid possible eMail duplication issues   
    before_save { |user| user.email = email.downcase }

    
    #Validation policy for users: name, password and eMail
    validates :name, presence: true, 
                     length: { minimum: 1, maximum: 50 }
    
    validates :password, presence: true,
                          :on => :create,
                          length: { minimum: 6, maximum: 100 }

    
    #validates_presence_of :email
    #validates_uniqueness_of :email
    #TODO - Must improve the validating eMail Regex for 'oli.@gmail..com'
    validates :email, presence: true, 
                      length: { minimum: 3, maximum: 100 },
                      #format: { with: /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i },
                      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                      #uniqueness: true
                      uniqueness: { case_sensitive: false }
  
    # Method to Authenticate users on controller 
    def self.authenticate(email, password)
      user = find_by_email(email)
      if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
        user 
      else
        nil
      end
    end
    
    # Method to encrypt users' passwords creating two db fields: pw_salt & pw_hash  
    def encrypt_password
      if password.present?
        self.password_salt = BCrypt::Engine.generate_salt
        self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  private
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged In !!!"
    else
      flash.now.alert = "Invalid eMail or Password"
      render "new"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged Out !!!"
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  #Static Page of the site - HOME
  def home
  end

  #Static Page of the site - HELP
  def help
  end

  #Static Page of the site - ABOUT
  def about
  end

  #Static Page of the site - ABOUT
  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # this controller handles user sing-up, sing-in and log-off, as well as all validations
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save 
      redirect_to root_url, :notice => "Signup !!!"
    else
      render "new"
    end
  end
  
  def show
    @user = User.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "tKiero Demo App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/layouts/_footer.html.erb
<footer>
	<div class="container">
		<!-- MyFooter row of 4 columns -->
		<div class="row">
			<div class="span8"> 
				<!-- 12 columns -->
				<div class="row">
					<div class="span2">
						<h4>About us</h4>
						<span class="label success">New</span>
						<a href="#">Team & Mentors & Board</a>
						<br>
						<a href="#">Customer Stories</a>
						<br>
						<a href="#">Jobs</a>
						<br>
						<a href="#">Press</a>
						<br>
						<a href="#">Copyright Policy</a>
						<br>
						<br>
						<p>Donec id elit non mi porta gravida at eget metus.</p>
					</div> <!-- /SPAN2 -->
					<div class="span2">
						<h4>Our Products</h4>
						<a href='http://www.buildoneideas.com'>AAA &amp; BBB</a>
						<br>
						<a href='http://www.buildoneideas.com'>CCC</a>
						<br>
						<a href='http://www.buildoneideas.com'>DDD</a>
						<br>
						<br>
						<p>Donec id elit non mi porta gravida at eget metus.</p>
					</div> <!-- /SPAN2 -->
					<div class="span2">
						<h4>Contact Us</h4>
						<a href='http://www.buildoneideas.com'>Contact Us</a>
						<br>
						<a href='http://www.buildoneideas.com'>Partner with Us</a>
						<br>
						<a href='http://www.buildoneideas.com'>Help Desk</a>
						<br>
						<br>
						<p>Donec id elit non mi porta gravida at eget metus.</p>
					</div> <!-- /SPAN2 -->
					<div class="span2">
						<h4>Legal info</h4>
						<a href="#">Legal Info</a>
						<br>
						<a href="#">Company</a>
						<br>
						<a href="#">Terms of Use & Service</a>
						<br>
						<a href="#">Privacy Policy </a>
						<br>
						<a href="#">Copyright Policy</a>
						<br>
						<br>
						<p>Donec id elit non mi porta gravida at eget metus.</p>
					</div> <!-- /SPAN2 -->
				</div>	<!-- 12 columns -->	
			</div>
			<div class="span pull-right">
				<h4>Stay in Touch</h4>
				<a href='http://www.twitter.com'>
				<img src="http://github.com/intridea/authbuttons/raw/master/png/twitter_32.png" alt="Twitter">
				</a>
				<a href='http://www.facebook.com'>
				<img src="http://github.com/intridea/authbuttons/raw/master/png/facebook_32.png" alt="Facebook">
				</a>
				<a href='http://plus.google.com'>
				<img src="http://github.com/intridea/authbuttons/raw/master/png/google_32.png" alt="Google+">
				</a>
				<br>
			</div> <!-- /SPAN2 -->
			<div class="span12 center"
				<br>
				<br>
				<br>
				<p>&copy; 2011-2012 All Rights Reserved. <a href='http://www.buildoneideas.com'>&reg;BuildOneIDeas</a> is a registered trademark of SETI Desarrollo Tecnologico S.L.</p>
				<%= link_to image_tag("b1IDeasLogo60x60.png", alt: "Build One IDeas"), 'http://www.buildoneideas.com/' %>
			</div>
		</div> <!-- /row 12 = 3 + 9 -->
	</div> <!-- /footer -->
</footer>

app/views/layouts/_header.html.erb
	<!-- NavBar
	-------------------------------------------------- -->
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
        	  <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" id="logo" href="<%= root_path %>">tKiero</a>
		  <!-- #<%= link_to "tKiero Demo App", '#', id: "logo" %> -->
          <div class="nav-collapse">
            <ul class="nav pull-right">
              <li class="active">
				<a href="<%= root_path %>"><i class="icon-home icon-white"></i> Home</a>
              </li>
              <li><%= link_to "About Us", about_path %></li>
			  <li><%= link_to "Contact", contact_path %></li>
              <li><%= link_to "Help", help_path %></li>
              <li><%= link_to "Log In", login_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

	<!-- Fix for Mobile Devices -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<%= render 'layouts/shim' %>    
	<!-- Le fav icon -->
    <link rel="shortcut icon" href="<%= asset_path "favicon.ico" %>">
  </head>
  <body>
    <%= render 'layouts/header' %>    
    <div class="container">
    		<!-- Checks if there is an user loged in and displays his info -->
    		<div id="user_nav">
    			<% if current_user %>
    				Logged in as <%= current_user.email %>
    				<%= link_to "log Out", logout_path %> 
    			<% else %>
    				<%= link_to "Sign Up", signup_path %> 
    				or
    				<%= link_to "Log In", login_path %> 
    			<% end %>
    		</div> 
    	
    		<!-- Div for Flash Messages-->    		
    		<% if flash.first %>
			<div class="alert alert-success">
	  			<button class="close" data-dismiss="alert">×</button>
		    		
		    		<!-- Displays all flash messages of the main app-->
		    		<% flash.each do |name, msg| %>
		    			<%= content_tag :div, msg, :id => "flash_#{name}" %>
		    		<% end %>
	    		</div>
    		<% end %>

    		<%= yield %>
    </div>
    <br>
    <br>
    <br>
    <br>
    <%= render 'layouts/footer' %>
	<div class="alert alert-info">
  		<button class="close" data-dismiss="alert">×</button>
  		<%= debug(params) if Rails.env.development? %>		
	</div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>

<h1>tKiero App</h1>
<p>
	This is Our Team, the crazy ones who think theycan change the world.
	We belive that there is a lot to disconver. Together. That's why we love to help people to bring their ideas to life.
	This is what we do in <a href="http://www.buildoneideas.com"> Build One IDeas</a>
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>tKiero App</h1>
<p>
	This is the Contact Page of  
	<a href="http://www.buildoneideas.com"> Build One IDeas</a>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>tKiero App</h1>
<p>
	If you need help with our site you can contact us at. 
	<a href="http://www.buildoneideas.com"> Build One IDeas</a>
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<!-- Hero-Unit Call To Action
-------------------------------------------------- -->
<div class="center hero-unit">
	<!-- MAIN CALL TO ACTION -->
	<h1>tKiero App</h1>
  	<h2>Si quieres algo, dilo bien alto !!!</h2>
	<p>This is the Home Page for one of the New Labs of 
    	<a href="http://www.buildoneideas.com"> Build One IDeas</a></p>
	<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-success" %>	
</div>
	
<br>
	
<!-- 3 Column 'Hero Page' row
-------------------------------------------------- -->
<div class="row calltoaction">
    <div class="span4">
    		<h2>Lo Kieres</h2>
		<p>Añade a la lista de tus sueños todo lo que quieras que te regalen o que quieres comprarte, cuando se te ocurra, donde se te ocurra, de la forma más fácil...</p>
    		<p><a class="pull-right btn" href="#">Ver detalles &raquo;</a></p>
		<!-- ><p><a class="btn btn-primary btn-large">Learn more »</a></p> -->
    </div>
    <div class="span4">
    		<h2>Lo Kompartes</h2>
    		<p>
    			Ordena tu lista y prioriza lo que quieres y quien te lo puede regalar.
    			Comparte tu lista con los que te kieren y pide un deseo !!! 
    		</p>
    		<p><a class="pull-right btn" href="#">Ver detalles &raquo;</a></p>
   </div>
    <div class="span4">
    		<h2>....y Konsigues tus sueños</h2>
    		<p>
    			Portate bien, sé bueno y konsigue tus sueños
    		</p>
    		<p><a class="pull-right btn" href="#">Ver detalles &raquo;</a></p>
    </div>
</div>
<!-- Line Break Separator -->	
<hr>


<!-- Carousel
-------------------------------------------------- -->

<div class="container">  <!-- MyFooter row of 4 columns -->
	<div class="row">
		<div class="span12">  <!-- 12 columns -->
			<div class="row-fluid">
				<div class="span">  <!-- 12 columns -->
					<!-- Carousel -->
					<div id="myCarousel" class="carousel">     <!-- Carousel items -->
						<div class="carousel-inner">
					  		<div class="active item"><img src="http://twitter.github.com/bootstrap/assets/img/bootstrap-mdo-sfmoma-01.jpg" alt>
					    			<div class="carousel-caption">
					    				<h4>Añade</h4>
					    				<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
					    			</div>
					    		</div>
					    		<div class="item"><img src="http://twitter.github.com/bootstrap/assets/img/bootstrap-mdo-sfmoma-02.jpg" alt>
					    			<div class="carousel-caption">
					    				<h4>Ordena</h4>
					    				<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
					    			</div>
					    		</div>
					    		<div class="item"><img src="http://twitter.github.com/bootstrap/assets/img/bootstrap-mdo-sfmoma-03.jpg" alt>
					    			<div class="carousel-caption">
					    				<h4>Comparte</h4>
					    				<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
						    		</div>
					    		</div>
					  	</div>
					  	<!-- Carousel nav -->
					  	<a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
					  	<a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/new.html.erb
<!-- Sign Up page -->
<% provide(:title, 'Sign Up') %>


<div class="center hero-unit">
	<!-- Sign Up Form -->
	<h2>tKiero App - Sign Up</h2>
	<p>
		Please fill in the form with to create a new account for tKiero App
		<br />
		tKiero App is one of current Build One IDeas Lab projects
	</p><br />

	<%= form_for @user do |f| %>
		<!-- Displays errors of the form, if any on -->
		<% if @user.errors.any? %>
			<div class="alert alert-error pull-left">
				<button class="close" data-dismiss="alert">×</button>		    		
				<p>You have entered invalid data on the form</p>
				<ul>
					<% for message in @user.errors.full_messages %>
						<li>	<%= message %></li>
					<% end %>
				</ul>
			</div>
		<% end %>
		
		<br />
		<div class="row">
  			<div class="span6">
				<p>
					<%= f.label :name %>
					<%= f.text_field :name, :placeholder => "name", autofocus:"true" %>
				</p>
				<p>
					<%= f.label :email %>
					<%= f.text_field :email, :placeholder => "eMail"  %>
				</p>
				<p>
					<%= f.label :password %>
					<%= f.password_field :password, :placeholder =>'password' %>
				</p>
				<p>
					<%= f.label :password_confirmation %>
					<%= f.password_field :password_confirmation, :placeholder =>'confirm password'%>
				</p>
				<br />
				<p><%= f.submit "Create your account...", class:"btn btn-large btn-success" %></p>
			</div>
			<div class="span4">
				<img src="http://placehold.it/350x330" alt="attention catching logo goes here">
			</div>
		</div>
	<% end %>
	<br />			
	<p>...ot if you already have an account, login here</p>
	<%= link_to "Log In here", login_path, class: "btn btn-large btn-success" %>

</div>
    

app/views/users/show.html.erb
<!-- Show User  Page -->
<% provide(:title, @user.name) %>

<h1>tKiero App</h1>
<div class="row">
  <aside class="span4">
    <section>
      <h2>
        <%= gravatar_for @user %>
        <%= @user.name %> <br/ >
		<%= @user.email %>
      </h2>
    </section>
  </aside>
</div>



<br/ >
<p class="center">
	This is Page is part of one of the Labs ob   
	<a href="http://www.buildoneideas.com"> Build One IDeas</a>
</p>